### ISSUE TITLE
Slight difference with Haskell version in substitution

### ISSUE THREAD

**Issue by hawnzug** [AndyShiue/pts#2]
In the post  [Simpler, Easier!](http://augustss.blogspot.tw/2007/10/simpler-easier-in-recent-paper-simply.html), in the case of substituting lambda and pi, when the bound variable coincide with v, it leaves the expression untouched but still substitute in the type.
```Haskell
subst :: Sym -> Expr -> Expr -> Expr
subst v x = sub
  where sub (Lam i t e) = abstr Lam i t e
        sub (Pi i t e) = abstr Pi i t e
        abstr con i t e =
            if v == i then
                con i (sub t) e
```
But in [Rust version](https://github.com/AndyShiue/pts/blob/688a1d0ab029c99ec72e19c3a149635b89c32b93/src/lib.rs#L342-L344) it simply keeps everything untouched.
```Rust
if bound == from {
    self.clone()
}
```
I'm new to pure type system so I'm not sure which version is correct but I think the Haskell version is more consistent with the process of finding free variables, which first removes the occurrence of bounded variable in inner part, then union the free variables in type. Would you take some time to review this part?

**Comment by AndyShiue** [comment]
You are right. The variable shouldn't be bound in its type.

**Comment by AndyShiue** [comment]
Should be fixed.
